### ISSUE TITLE
bandcamp branding

### ISSUE THREAD

**Issue by muzzol** [sethcottle/littlelink#10]
I've added bandcamp to my collection.

here's the icon:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path fill="#FFF" d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm48.2 326.1h-181L199.9 178h181l-84.7 156.1z"/></svg>
`

and brand colour is **#61929c** so css should be something like:

```
/* bandcamp */
.button.button-bandcamp {
  color: #FFFFFF;
  background-color: #61929c }
.button.button-bandcamp:hover,
.button.button-bandcamp:focus {
  filter: brightness(90%) }

```

thanks for you great project

**Comment by sethcottle** [comment]
I'll get this added, thank you! 👍

**Comment by sethcottle** [comment]
Closing! Getting this added into a small update this week! Thanks again!
