### ISSUE TITLE
New Website to add - Etsy

### ISSUE THREAD

**Issue by MrPresident2** [sethcottle/littlelink#110]
Hello

Is there a way to add Etsy store to littlelink?

**Comment by sethcottle** [comment]
Hi @MrPresident2 , you'll find that LittleLink has support for Etsy by default.

```
<!-- Etsy -->
<a class="button button-etsy" href="#" target="_blank" rel="noopener" role="button"><img class="icon" src="images/icons/etsy.svg" alt="">Shop on Etsy</a><br>
```

![image](https://github.com/sethcottle/littlelink/assets/1301949/3fba3958-4b10-4b60-8d9e-2fad30eac50e)
