### ISSUE TITLE
Add Request

### ISSUE THREAD

**Issue by marvinto23** [sethcottle/littlelink#12]
If possible please add a TikTok and E-Mail button because i cant do it myself. Thanks

**Comment by sethcottle** [comment]
I think those are great requests, I'll get those added. Will tag you and close this thread as soon as it's done.

**Comment by sethcottle** [comment]
@marvinto23 Added! You can[ view the commit here](https://github.com/sethcottle/littlelink/commit/8425f9dd556e98d5f8b266fb388ab720f9b88673).
