### ISSUE TITLE
logo idea

### ISSUE THREAD

**Issue by anderspitman** [sethcottle/littlelink#120]
You probably already considered this and decided against it, but if you rotated the logo 90 degrees the L's would sort of look like the angle brackets of an HTML link.

**Comment by sethcottle** [comment]
Thanks for the suggestion @anderspitman, we had actually done a brief design exercise when the logo was redone a while back and I just looked at the file and that was... not a configuration that was even looked at. Some good food for thought! I might play around with it a bit more and actually try it out, I think the L's could be reconfigured slightly to make it a little more appealing when rotated, but very roughly. 👇😀

![LittleLink-Rotated](https://github.com/sethcottle/littlelink/assets/1301949/ad6cd765-7da0-410a-bb09-6e2cc3741325)
