### ISSUE TITLE
Add version to index.html or VERSION file

### ISSUE THREAD

**Issue by muzzol** [sethcottle/littlelink#122]
I installed littlelink some time ago and I can't find the version I used.

It would be nice to have a quick and easy way to identify the running version, either with a comment in index.html or just a VERSION file packaged with the sources.

thanks a lot for your time.

**Comment by sethcottle** [comment]
That's a great idea @muzzol , thanks for taking the time to suggest it! I'm working on a few updates and will include this in it!

**Comment by muzzol** [comment]
wow, that was really fast!

happy coding :)
