### ISSUE TITLE
link to openstreetmap profile

### ISSUE THREAD

**Issue by atchisson** [sethcottle/littlelink#125]
Hello there,

first of all, thanks for the nice product !

i would like to add a openstreetmap button, as i'm a active ish contributor on that, is it possible ?

the profile link looks something like this : https://www.openstreetmap.org/user/atchisson

here is a link to the logo : https://wiki.openstreetmap.org/wiki/File:Public-images-osm_logo.svg

thanks !

**Comment by atchisson** [comment]
maybe https://github.com/sethcottle/littlelink-extended would be more appropriate, there was a PR for it but it was closed

**Comment by sethcottle** [comment]
This would be worthwhile for LL Extended! I'll find the PR that was previously closed and either pull that in or add in a new PR.

**Comment by sethcottle** [comment]
@atchisson added to [LittleLink Extended](https://github.com/sethcottle/littlelink-extended)!
