### ISSUE TITLE
Line breaks in display name are too large.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [sethcottle/littlelink#127]
As a downstream issue states:

<blockQuote>

### LinkStack version

https://linksta.cc/

### Description

> ![Screenshot_20240417_143133](https://github.com/LinkStackOrg/LinkStack/assets/42837531/2441c29b-7b97-4325-a440-e3114a7dabcd)

### Details about your system

<table><tr>
	<th>OS</th>
	<td><a href='https://download.fedoraproject.org/pub/fedora/linux/releases/test/40_Beta/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-40_Beta-1.10.iso'><code>cpe:/o:fedoraproject:fedora:40</code></a></td></tr></table>

### How to reproduce

Visit https://linksta.cc/studio/links or https://linksta.cc/@RokeJulianLockhart.

### Possible Solution

Make the line breaks render like regular enlarged text's does. I dunno what CSS you're using to style it, but check that you're using `em` instead of static `px` definitions.

</blockQuote>

I've been informed that this is an upstream problem, per https://github.com/LinkStackOrg/LinkStack/issues/759#issuecomment-2408482499:

> We are using upstream littlelink as the base for our styling. This may be resolved using a custom theme.
> 
> We will continue using the current styling format for now, until we replace it. When we switch our layout system, this will be revised along with some other styling and spacing issues that the current layout has.

**Comment by sethcottle** [comment]
Thanks, I'll try to find some time to look into this over the weekend. I've been clean some of the CSS up anyway!

**Comment by sethcottle** [comment]
Resolved in the LittleLink v3 overhaul! Thanks for the kick to get this done, had been on the list for a long long while, haha. TL;DR moved away from the old Skeleton CSS base we were using to a purpose-built solution that meets the needs of LittleLink more and makes everything modular and easier to maintain.

https://github.com/sethcottle/littlelink/commit/9f000923d5e13f9548d3bcafa7d41f99796c5a0a
