### ISSUE TITLE
whatsapp branding 

### ISSUE THREAD

**Issue by xeitu** [sethcottle/littlelink#13]
Would be great to have whatsapp too

Best regards!

**Comment by xeitu** [comment]
Is there any guideline in order to help you generating de SVG code of the icon?

**Comment by sethcottle** [comment]
@xeitu great suggestion, I'll get this added! I typically pull assets and branding guidelines directly from each brand to avoid any inconsistencies, I'll be able to get this added in this week.

**Comment by sethcottle** [comment]
Finished, sorry for the long long long delay on this!

https://github.com/sethcottle/littlelink/commit/dc6a3a222ad24b5e87a61ee3f28db62f8cb9a808
