### ISSUE TITLE
Add Idea

### ISSUE THREAD

**Issue by marvinto23** [sethcottle/littlelink#22]
Hello,

could you Integrate Teamspeak 3 and Tellonmy too?

thanks a lot :)

**Comment by sethcottle** [comment]
Hey @marvinto23 ! I'm not quite sure these would be great additions to default to the masses. We try to keep our default to globally and regionally popular services that we feel would be a value add for the majority of those using LittleLink for the first time and not present them with an overwhelming number of services. That's pretty subjective and I'll likely be included some governance on this in the future. Given it's pretty easy to add your own, please feel free to fork LittleLink and add them in your own repo! Let me know if you need help adding them to a personal project!
