### ISSUE TITLE
Avoid icons folder on root level

### ISSUE THREAD

**Issue by thrdroom** [sethcottle/littlelink#31]
Please consider one of the three things:

1. Merge folder "icons" with folder "images". As both just hold images
2. Make folder "icons" a subfolder of images.
3. Rename folder "icons" into something else

**The reason for my request is because of this**

_Default installations of Apache usually alias /icons to Apache’s icons directory which cannot be overridden in an .htaccess file. If you do not control the Apache configuration of a server, and for maximum compatibility, it is always best to never have an /icons directory at a website’s root level._

Avoiding the use of "icons" folder on root level would just improve overall compatability with webservers.

Thanks in advance

**Comment by sethcottle** [comment]
This is great feedback, thank you! I'll definitely work on implementing this change.

**Comment by sethcottle** [comment]
Resolved by moving `icons` to `images/icons`. Thanks again! Here's the commit, https://github.com/sethcottle/littlelink/commit/b9b5a86496507538845103dae924a9bdd601a84b !
