### ISSUE TITLE
Any plans for analytics integration?

### ISSUE THREAD

**Issue by frazras** [sethcottle/littlelink#38]
I could see it would be create to have drop in for google analytics to track link clicks,

**Comment by sethcottle** [comment]
Dropping in analytics services like Google Analytics are typically pretty straight forward. I personally don't believe it needs to be added as a template to the base index.html. 

There are so many analytic services being used, keeping it removed and squarely on the shoulders of those wanting to drop something in seems like the right approach here. For most you just drop a copy and paste script right into the <head>.
