### ISSUE TITLE
Addition of Two Links

### ISSUE THREAD

**Issue by brnt-toast** [sethcottle/littlelink#42]
Thoughts about Cash App and Stream Labs being added as links?
If approved, I wouldn't mind working on it and sending a PR

**Comment by sethcottle** [comment]
Hey @brnt-toast ! Actually, the recent PR #40 added in Cash App CSS and a few icons (default, Euro, and BTC). So be sure to check that out!

Streamlabs may be a good addition? I know it's super popular, but not something I particularly use. Just to get a little more clarification on use cases, would the goal just be for Streamlabs themed branding that would typically be used to get to their custom donations page that is powered by Streamlabs?
