### ISSUE TITLE
Internet Archive logo?

### ISSUE THREAD

**Issue by markcharlesobrien** [sethcottle/littlelink#59]
Hello, I would like to use your template, but I am a media preservationist with a large library of stuff on The Internet Archive and that would be the first thing in my list of links. Would it be possible to get an Internet Archive icon?

**Comment by sethcottle** [comment]
Hi @markcharlesobrien ! Take a look at this documentation from the Wiki on adding your own brands to your LittleLink fork! https://github.com/sethcottle/littlelink/wiki/Adding-custom-buttons-to-your-own-fork

We try to not include an overwhelming amount of brands in the default repo, especially ones that have more rare use cases, like the Internet Archive brand in your use case!

Let me know if that answers your questions or if you need help with your own LittleLink fork!
