### ISSUE TITLE
How to use the Signal button

### ISSUE THREAD

**Issue by neldonado** [sethcottle/littlelink#64]
Do you have any examples of how one would use the signal button? What would you put for the link?

        <a class="button button-signal" href="#" target="_blank" rel="noopener">
            <img class="icon" src="images/icons/signal.svg" alt="Signal Logo">Signal</a>
        <br>

**Comment by sethcottle** [comment]
Signal does support `signal.me` links. Right now those links will expose your phone number, but I believe they're working on username links for the future. The format for those are: `https://signal.me/#p/+countrycodeandphonenumber`

I've also seen them used for Signal Group links to join a group, like this:

![Screenshot_20220914-224402.png](https://user-images.githubusercontent.com/1301949/190301343-76a5e79f-46ee-425b-819e-91ea310b3e92.png)

Alternatively, people have also made standalone pages that tell people how to start a Signal conversation with them and name them something like `signal.html`.

**Comment by neldonado** [comment]
Thank you for the quick reply and detailed examples.
