### ISSUE TITLE
Script flagged as malware

### ISSUE THREAD

**Issue by FaisalAhmed123** [sethcottle/littlelink#84]
In phpstan.phar there seems to be a command being flagged as malware (php.shell.php.eval.githubusercontent). Screenshot attached 
https://imgur.com/a/CZ61eLP

**Comment by sethcottle** [comment]
@FaisalAhmed123 This looks like an issue with your own fork of LittleLink where you've added `vendor/phpstan/`. By default this isn't part of the the LittleLink repository, you might want to open an issue with [phpstan](https://github.com/phpstan/phpstan).
