### ISSUE TITLE
overflow? long text support

### ISSUE THREAD

**Issue by stephenajulu** [sethcottle/littlelink#9]
Hi, i would like to have buttons that support long text eg overflow moves to the next line

**Comment by sethcottle** [comment]
Would prefer you integrate overflow for buttons in your own fork. I believe it directly negates the goal of LittleLink having the support built-in. I want to encourage the use of short text to help keep external links as readable and uniform as possible. Ideally, your text is really no longer than _Find us on Facebook_. You also have a little wiggle room to change the button width to something larger than 300px, which was just chosen to help support as many mobile screen sizes as possible.

**Comment by stephenajulu** [comment]
Hi, i understand what you mean but i am looking to make this a linktree alternative hence i'll have links to posts and such, hence requiring the text to move to the next line.

**Comment by stephenajulu** [comment]
ok how can i integrate it, I am a beginner
