### ISSUE TITLE
Buttons don't auto-adjust height when multiline

### ISSUE THREAD

**Issue by thibaultmol** [sethcottle/littlelink#90]
If you have an amount of text that is larger than the max amount of chars for one line. 

I feel like it should automatically adjust the height of the button to accommodate for the text

![Screenshot_1593](https://user-images.githubusercontent.com/1010226/233716003-0bbb4c7c-baef-45ee-b9a7-c4019cdaa407.png)

**Comment by sethcottle** [comment]
Looks like you're using a community fork of LittleLink, LittleLink-Custom. You should [open an issue in their repository](https://github.com/JulianPrieber/littlelink-custom) if you'd like to see that functionality.

However, just to note. LittleLink gives you about ~21 characters to work with for your button text (depending on the characters themselves). Not having auto-wrapping is mostly an encouragement to keep button content concise and actionable, i.e. "Find Us On Facebook"

For those who find this issue and would like to do so, it's pretty straightforward to enable button wrapping in LittleLink.

Open `brands.css` and head over to the Buttons section. Under `.button,` you'll find `height: 48px` change that to `height: 100%;` to scale with all the content you'll be adding. Add `padding: 12px 0px 12px 0px;` as a new line underneath to give the button some padding for when it wraps, right now it's relying on `line-height` to give it artificial padding. Then change your `line-height: 48px;` to something like `line-height: 24px;` to tighten that line break up to keep it readable.

You can also tweak the width, like `width: 100%;` to give yourself some more wiggle room. By default it's a hard coded 300px as a safety point for small devices. I'm sure the buttons could be improved to be more _responsive_.

**Comment by thibaultmol** [comment]
Yeah, i actually did, but they thought it was an upstream thing. But thx for the explenation, might help them implement maybe. I dunno what they'll do https://github.com/JulianPrieber/littlelink-custom/issues/405#event-9069820196

**Comment by sethcottle** [comment]
That's totally fair. I'll reopen this for right now to see if we can snag some additional commentary from Julian or anyone else in the community. It was a pretty deliberate choice of mine in the beginning, but if it's something we want to do upstream on this repo, we can absolutely do that!

**Comment by sethcottle** [comment]
@thibaultmol 👋  [ae5e73d](https://github.com/sethcottle/littlelink/commit/ae5e73d51e1b892d462bccff51d97ce4435bae80) added in automatic height adjustment to help with localization issues. Also includes some `focus` state updates for increased accessibility.
